# Site settings
title: Iran University of Science and Technology
course_name: Natural Language Processing
course_description: In this course we aim to familiarize students with the kind of problems NLP deals with and various techniques to tackle them. For the most part we follow the <a href="https://web.stanford.edu/~jurafsky/NLPCourseraSlides.html">lecture slides</a> from the Stanford Coursera course by Dan Jurafsky and Christopher Manning. 
course_semester: "Spring 2019 "
description: |
    Instructor: Sauleh Eetemadi

message: #Register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/nlp97" # the subpath of your site, e.g. /blog/
url: "http://sauleh.github.io/nlp97" # the base hostname & protocol for your site
githubdir: 

# Author/user information
email: instructor-first-name@iust.ac.ir
twitter_username: sauleh_e 
github_username:  sauleh
authorurl: "http://sauleh.github.io/"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"



plugins:
    - jekyll-jalali
